services:

  postgres:
    image: postgres:17
    container_name: smx-postgres
    environment:
      POSTGRES_USER: smx
      POSTGRES_PASSWORD: smx
      POSTGRES_DB: smx_ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smx -d smx_ecommerce"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: smx-keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-mem
    ports:
      - "8180:8080"
    volumes:
      - ./infrastructure/keycloak:/opt/keycloak/conf/import
    depends_on:
      postgres:
        condition: service_healthy

  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: smx-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  mailhog:
    image: mailhog/mailhog
    container_name: smx-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
  es_data:
