-- Crea tutti gli schemi in H2 prima che Hibernate generi le tabelle con ddl-auto=create-drop
CREATE SCHEMA IF NOT EXISTS SMX_CATALOG;
CREATE SCHEMA IF NOT EXISTS SMX_CART;
CREATE SCHEMA IF NOT EXISTS SMX_ORDER;
CREATE SCHEMA IF NOT EXISTS SMX_PAYMENT;
CREATE SCHEMA IF NOT EXISTS SMX_WAREHOUSE;
CREATE SCHEMA IF NOT EXISTS SMX_SHIPMENT;
CREATE SCHEMA IF NOT EXISTS SMX_REVIEW;
CREATE SCHEMA IF NOT EXISTS SMX_ANALYTICS;
